site_name: MapleSim
site_url: https://shenzhen-robotics-alliance.github.io/maple-sim/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  logo: media/team_logo.png
  favicon: media/team_logo.png
  icon:
    annotation: material/arrow-right-circle 
  features:
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.code.select.title
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - announce.dismiss
    - navigation.instant
    - navigation.footer


# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Page tree


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.details


# sidebar settings
nav:
    - Home: index.md
    - Simulation Details : simulation-details.md
    - Installation: installing-maple-sim.md
    - Using the Simulated Arena: using-the-simulated-arena.md
    - Swerve Simulation: 
        - Overview: swerve-simulation-overview.md
        - Simple Swerve Sim: swerve-sim-easy.md
        - Hardware Abstraction Sim : swerve-sim-hardware-abstraction.md
    - Simulating Intake: simulating-intake.md
    - Simulating Opponent Robots: simulating-opponent-robots.md
    - Simulating Projectiles: simulating-projectiles.md
    - Reefscape Simulation: reefscape.md 
    - Contributing: CONTRIBUTION.md
    - Release Notes: ./release-notes/version0.3.0-beta2.md